language: elixir

stages:
  - lint
  - test

jobs:
  include:
    - script: mix credo --strict
      name: "Credo"
      stage: lint
      elixir: '1.13'
      otp_release: '24.0.0'
    - elixir: '1.13'
      otp_release: '24.0.0'
      script: mix test
      stage: test